no user select, draggable always false,
DarthVanger/ghost-of-kyiv pull request #62
Opened 2023-03-04 21:43 UTC by 19thanks96

-created folder 'music' and add all sounds there;
- forbid moving pictures when holding the mouse;
- in portrait mobile orientaition change zoom;
- prohibited highlighting the content of the game.

2023-03-06 12:46 UTC, Gehinom requested changes
Change pls names of variables:
soundStart to soundMainTheme;
soundEnd to soundLevelComplete;
and turn the volume of soundLevelComplete down to ~0.5. Now its too loud

2023-03-06 12:53 UTC, Gehinom reviewed
soundShot to soundRocketShot;
sountHit to soundRocketHit;
soundExplosion to soundEnemyDieExplosion;
soundLauth to soundGameOver;

2023-03-08 07:34 UTC, 19thanks96 commented
> Now its too loud
0.5 its too loud. 0.3-0.4 its good

2023-03-08 07:55 UTC, Gehinom approved these changes

2023-03-08 14:47 UTC, Alianshark approved these changes

2023-03-08 14:57 UTC, merged