random enemy and scroll in move
DarthVanger/ghost-of-kyiv pull request #75
Opened 2023-03-22 22:12 UTC by 19thanks96

2023-03-24 00:58 UTC, DarthVanger commented
Please provide description for this pull request.

2023-03-24 01:25 UTC, DarthVanger commented
This pull request has conflicts with fresh `master` branch.

### Please merge `master` into your branch

1. Switch to `master` with `git checkout master`.
2. Pull master with `git pull master`.
3. Switch to your branch with `git checkout randomenemy`.
4. Merge `master` into your branch with `git merge master`. It will show conflicts - fix them.
4.1. Use `git add` to mark resolved files.
4.2. Use `git commit` to finish the merge.
4.3. Use `git push` to push the merged branch with conflicts fixed.
5. Refresh pull request tab on github.com, check if it doesn't show conflicts anymore.
6. ✅ 

![image](https://user-images.githubusercontent.com/6686679/227400683-c863f68d-44a8-4455-bd82-789be9a50eab.png)

The conflicts happened because Dimon's Pull Request was merged.

2023-03-24 01:27 UTC, DarthVanger requested changes
Fix merge conflicts plz

2023-03-27 09:29 UTC, Alianshark commented on app.js
> +  if (airfighter.x > airfighter.width) {
what is that doing?

2023-03-27 23:41 UTC, 19thanks96 reviewed
LGTM

2023-03-28 09:12 UTC, Alianshark approved these changes
LGTM

2023-04-04 11:41 UTC, Gehinom approved these changes

2023-04-06 18:14 UTC, DarthVanger approved these changes

2023-04-06 18:15 UTC, merged